name: deploy to server

on:
  push:
    branches:
      - server

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                run_install: true
            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: pnpm

            - name: Build
              run: pnpm run build

            - name: Deploy to Server
              uses: mai-space/action-sshpass-rsync@v1
              with:
                host: ${{ secrets.SSH_HOST }}
                user: ${{ secrets.SSH_USERNAME }}
                port: 223
                pass: ${{ secrets.WWW_DEPLOY_KEY }}
                local: "dist/"
                remote: "/www/wwwroot/website.cn/"